import time
print("██╗░░██╗███████╗██╗░░░██╗██╗  ██╗██╗███╗░░░███╗  ███████╗░█████╗░░█████╗░██╗░░██╗██╗")
print("██║░░██║██╔════╝╚██╗░██╔╝██║  ██║╚█║████╗░████║  ╚════██║██╔══██╗██╔══██╗██║░░██║██║")
print("███████║█████╗░░░╚████╔╝░██║  ██║░╚╝██╔████╔██║  ░░███╔═╝███████║██║░░╚═╝███████║██║")
print("██╔══██║██╔══╝░░░░╚██╔╝░░╚═╝  ██║░░░██║╚██╔╝██║  ██╔══╝░░██╔══██║██║░░██╗██╔══██║╚═╝")
print("██║░░██║███████╗░░░██║░░░██╗  ██║░░░██║░╚═╝░██║  ███████╗██║░░██║╚█████╔╝██║░░██║██╗")
print("╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝  ╚═╝░░░╚═╝░░░░░╚═╝  ╚══════╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝")
time.sleep(1)
print("Check Out My Blue Themes for all major browsers and VS Code @ https://zfauser.github.io/zachs-blue-theme/")
time.sleep(1)
print("Programming/Scripting languages: bash, python, html, css (tailwind), javascript (jquery, react)")
time.sleep(1)
print("Learning: dart (flutter), sql, nosql")
time.sleep(1)
print("Certifications: Oracle Cloud Infrastructure Foundations 2021 Certified Associate, IBM Cloud Essentials")
time.sleep(1)
print("Currently studing for: Azure AZ-104")
time.sleep(1)
print("Personal Site: zachfauser.com")
time.sleep(1)
print("Finance/Banking Themed Wordle Clone: bankle.zachfauser.com")
time.sleep(1)
